name: Compile Project

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '1.8'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Compile with Gradle
      run: ./gradlew assembleDebug -PMovieDBApiKey="${{ secrets.IMDB_API_KEY }}"
      env:
        IMDB_API_KEY: ${{ secrets.IMDB_API_KEY }}
