name: Compile Project

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8.0.462+8'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Compile with Gradle
      run: ./gradlew assembleDebug -PMovieDBApiKey="${{ secrets.IMBD_API_KEY }}"
      env:
        IMBD_API_KEY: ${{ secrets.IMBD_API_KEY }}
